services:
  archiver:
    build:
      context: .
      dockerfile: archiver/Dockerfile
    image: gcr.io/waddell-wind/waddell_wind-archiver:latest
    env_file: ".env"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro # Mounts your local gcloud credentials

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file: ".env"
    ports:
      - 5000:5000
