services:
  archiver:
    build:
      context: .
      dockerfile: archiver/Dockerfile
    env_file: ".env_docker_local"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro # Mount your local gcloud credentials

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file: ".env_docker_local"
    volumes:
      - ${LOCAL_IMAGE_STORE}:${DOCKER_IMAGE_STORE}
    ports:
      - 5000:5000
