services:
  archiver-local:
    build:
      context: .
      dockerfile: archiver/Dockerfile
    env_file: ".env"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro # Mount your local gcloud credentials

  archiver-cloud:
    build:
      context: .
      dockerfile: archiver/Dockerfile
    env_file: ".env"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file: ".env"
    volumes:
      - ${LOCAL_IMAGE_STORE}:${DOCKER_IMAGE_STORE}
    ports:
      - 5000:5000
