services:
  archiver:
    build:
      context: .
      dockerfile: archiver/Dockerfile
    env_file: ".env"
    volumes:
      - ${LOCAL_IMAGE_STORE}:${DOCKER_IMAGE_STORE}

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file: ".env"
    volumes:
      - ${LOCAL_IMAGE_STORE}:${DOCKER_IMAGE_STORE}
    ports:
      - 5000:5000
